config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants
  resources :restaurants do
    resources :reviews
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, :dependent => :destroy
    validates :name, presence: true
    validates :address, presence: true
    validates :category, presence: true, inclusion: {in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: {in: [0,1,2,3,4,5]}, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
        
    end

    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @restaurant = Restaurant.find(params[:restaurant_id])
        @reviews = @restaurant.reviews.all
    end

    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        if @review.save
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
        
    end

    private

    def review_params
        params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> List Restaurant </h1>

<ul>
    <%@restaurants.each do |restaurant|%>
    <li> <a href="../restaurants/<%=restaurant.id%>"> <%= restaurant.name%> </li>
    <%end%>
</ul>
<br>
<a href="../restaurants/new"> Create a new restaurant </a>

app/views/restaurants/new.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label(:name, "name:") %>
  <%= f.text_field :name %><br>
  <%= f.label(:address, "address:") %>  
  <%= f.text_field :address %> <br>
  <%= f.label(:category, "category:") %>  
  <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"]%><br>
  <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
  <%= f.submit "Submit Restaurant", class: "btn btn-primary" %>
  
<% end %>

app/views/restaurants/show.html.erb
<%=@restaurant.name%>
<br>
<a href="./"> Go back to the Restaurant List </a>
<br>
<a href="<%=params[:id]%>/reviews"> I want to see the reviews ! </a>

app/views/reviews/index.html.erb
<h1> List Reviews for <%=@restaurant.name%> </h1>
<ul>
    <%@reviews.each do |review|%>
     <li class="list-group-item"><%= review.content %></li>
     <%end%>
</ul>
<a href=".."> Go back to the list of restaurants </a>
<br>


<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <%= f.label(:content, "content:") %>
  <%= f.text_field :content %><br>
  <%= f.label(:rating, "rating:") %>  
  <%= f.number_field( :rating, in:1.0..5.0, step: 1.0) %> <br>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
  
<% end %>